import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Scanner } from '@yudiel/react-qr-scanner';
import { AlertTriangleIcon, XCircleIcon } from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from '@/core/components/ui/dialog';
import { Alert, AlertDescription, AlertTitle } from '@/core/components/ui/alert';
import { Button } from '@/core/components/ui/button';
import { parseRemoteSyncQR, type RemoteSyncConfigShare } from '@/core/remote-sync/remoteSyncQRPayload';

function describeScannerError(err: unknown): string {
  if (err instanceof Error) {
    // Surface the underlying DOMException name when available — these are the
    // names browsers use for getUserMedia failures.
    if (err.name === 'NotAllowedError') {
      return 'Camera permission denied. In iOS Safari, grant access in Settings → Safari → Camera, then reload.';
    }
    if (err.name === 'NotFoundError' || err.name === 'OverconstrainedError') {
      return 'No camera available on this device.';
    }
    if (err.name === 'NotReadableError') {
      return 'Camera is in use by another app. Close other camera apps and try again.';
    }
    if (err.name === 'SecurityError') {
      return 'Browser blocked camera access. This usually means the page is not served over HTTPS.';
    }
    return `${err.name}: ${err.message}`;
  }
  return typeof err === 'string' ? err : 'Unknown scanner error.';
}

interface RemoteSyncScanQRDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onScanned: (config: RemoteSyncConfigShare) => void;
}

export function RemoteSyncScanQRDialog({ open, onOpenChange, onScanned }: RemoteSyncScanQRDialogProps) {
  const [error, setError] = useState<string>('');
  // iOS Safari (and most other browsers) refuse getUserMedia on insecure
  // contexts. Detect this up front so we can show a useful hint *before* the
  // user wastes time trying to scan.
  const insecureContext = useMemo(() => {
    if (typeof window === 'undefined') return false;
    return !window.isSecureContext;
  }, []);
  // Latch so we don't fire onScanned more than once if the camera reads the
  // same code twice in the small window before the dialog closes.
  const consumedRef = useRef(false);
  // Stable refs so the Scanner doesn't re-init on every render.
  const onScannedRef = useRef(onScanned);
  const onOpenChangeRef = useRef(onOpenChange);
  useEffect(() => {
    onScannedRef.current = onScanned;
    onOpenChangeRef.current = onOpenChange;
  });

  useEffect(() => {
    if (open) {
      consumedRef.current = false;
      setError('');
    }
  }, [open]);

  const handleScan = useCallback((results: { rawValue: string }[]) => {
    if (consumedRef.current) return;
    const first = results[0];
    if (!first) return;
    const result = parseRemoteSyncQR(first.rawValue);
    if (!result.ok) {
      setError(result.reason);
      return;
    }
    consumedRef.current = true;
    onScannedRef.current(result.config);
    onOpenChangeRef.current(false);
  }, []);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle>Scan sync config</DialogTitle>
          <DialogDescription>
            Aim the camera at a QR generated by another scout's Remote Sync &gt; Share via
            QR screen.
          </DialogDescription>
        </DialogHeader>

        {insecureContext && (
          <Alert variant="destructive">
            <AlertTriangleIcon />
            <AlertTitle>Camera blocked — insecure context</AlertTitle>
            <AlertDescription className="space-y-2 text-xs">
              <p>
                This page is not served over HTTPS. iOS Safari and most other mobile
                browsers refuse camera access on plain <code>http://</code> URLs unless
                the host is exactly <code>localhost</code>.
              </p>
              <p>
                To scan from a phone during dev, serve over HTTPS — e.g. <code>vite --https</code>,
                <code>netlify dev --https</code>, or a tunnel like <code>ngrok http 5173</code>.
                In production, Maneuver is served over HTTPS so this hint won't appear.
              </p>
            </AlertDescription>
          </Alert>
        )}

        <div className="h-64 w-full overflow-hidden rounded-lg md:h-80">
          {open && !insecureContext && (
            <Scanner
              components={{ finder: false }}
              scanDelay={100}
              styles={{
                video: {
                  borderRadius: '7.5%',
                  width: '100%',
                  height: '100%',
                  objectFit: 'cover'
                }
              }}
              onScan={handleScan}
              onError={(err) => setError(describeScannerError(err))}
            />
          )}
        </div>

        {error && (
          <p className="flex items-start gap-1 text-sm text-destructive">
            <XCircleIcon className="size-4 shrink-0 translate-y-0.5" />
            <span>{error}</span>
          </p>
        )}

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
